### ISSUE TITLE
Any ETA for supporting Filament3?

### ISSUE THREAD

**Issue by mohamedsabil83** [yepsua/filament-rating-field#15]

**Comment by braaam** [comment]
I've done a quick fix to make it work with filament v3. use on your own risk, it has not been tested extensively :)

2 simple changes:

https://github.com/yepsua/filament-rating-field/commit/6d071f1954ce94fac431c904710faa6fb7cdb345
https://github.com/yepsua/filament-rating-field/commit/a7dc18212a0ee1b25068fbafb3685954e29b9f79

**Comment by mohamedsabil83** [comment]
Yes, @braaam. I did that when I did not receive any action. There's another [rating package](https://filamentphp.com/plugins/ibrahim-bougaoua-star-rating), but I still need to try it.

**Comment by braaam** [comment]
@mohamedsabil83 thanks for sharing. At first glance it looks like you can only configure the number of stars with the rating package. filament-rating-field provides a lot more flexibility out of the box which is great for different purposes.

**Comment by gboquizosanchez** [comment]
I have put a pull request [here](https://github.com/yepsua/filament-rating-field/pull/16) to update this package to filamentphp 
 version 3.
 
 I hope gonna be merged soon. If not, I'll make a fork of it.

**Comment by gboquizosanchez** [comment]
Until v3 is supported, I have made a supporting package. You can found it [here](https://github.com/gboquizosanchez/filament-rating-field).

Cheers!
