### ISSUE TITLE
Signature of $width/width()/getWidth() has changed

### ISSUE THREAD

**Issue by renderse7en** [yepsua/filament-rating-field#19]
Laravel 11.10
Filament v3.2.91
filament-rating-field v0.4.0

I added a simple `RatingColumn::make('difficulty')` to a table and receive the following error when attempting to load that resource's index page:

> Type of Yepsua\Filament\Tables\Components\RatingColumn::$width must be Closure|string|int|null (as in class Filament\Tables\Columns\Column)

I was able to make it work by going down into `Yepsua\Filament\Tables\Components\RatingColumn.php` class and fixing the `$width` property and the `width()` and `getWidth()` methods to match the signatures in `Filament\Tables\Columns\Concerns\HasWidth.php`.

**Comment by abdosaeedelhassan** [comment]
Hi @renderse7en,
can you describe what changes you make to git it work, can do it with closure so no need to change package code
