### ISSUE TITLE
RatingColumn for table

### ISSUE THREAD

**Issue by aeq-dev** [yepsua/filament-rating-field#7]
Hi,
Thanks for this awesome package,
any plan to add it as column field for table ?

**Comment by aeq-dev** [comment]
Also can we set a default value if the record is already rated ? useful for edit / view page

**Comment by billmn** [comment]
Agree, a rating column could be very useful!

**Comment by kingmaker-agm** [comment]
Hi Package owner @oyepez003 , Kindly release this latest changes 74a943bcfcb40336b88a0665daff1a39112aeef0 into a version `v0.1.2` by adding Tag in the Github.

I'm eagerly waiting for the Table Column implementation of Star Rating field.

**Comment by oyepez003** [comment]
@kingmaker-agm done with the next tag: https://github.com/yepsua/filament-rating-field/releases/tag/v0.2.0 @aymanalhattami

**Comment by kingmaker-agm** [comment]
Thanks for the quick action @oyepez003 👍
