### ISSUE TITLE
Tooltips not working

### ISSUE THREAD

**Issue by sewid** [yepsua/filament-rating-field#9]
When using the example code from the docs for the tooltips, the tooltips are not shown when hovering in Chrome and Safari when using macOS.

**Comment by oyepez003** [comment]
We use the tooltips provided by the filament components. Could you make sure the tooltips work as is expected in other components too?

**Comment by sewid** [comment]
I can't find tooltips when using regular filament fields. I only find them (in their docs) for the Table Builder - and I use only the Form Builder.
